namespace GeometryDash.Server.Levels;

public enum OfficialSong
{
    StayInsideMe = -1,
    StereoMadness = 0,
    BackOnTrack = 1,
    Polargeist = 2,
    DryOut = 3,
    BaseAfterBase = 4,
    CantLetGo = 5,
    Jumper = 6,
    TimeMachine = 7,
    Cycles = 8,
    xStep = 9,
    Clutterfunk = 10,
    TheoryOfEverything = 11,
    ElectromanAdventures = 12,
    Clubstep = 13,
    Electrodynamix = 14,
    HexagonForce = 15,
    BlastProcessing = 16,
    TheoryOfEverything2 = 17,
    GeometricalDominator = 18,
    Deadlocked = 19,
    Fingerdash = 20,
    Dash = 21,
    Explorers = 22,
    TheSevenSeas = 23,
    VikingArena = 24,
    AirborneRobots = 25,
    Secret = 26,
    Payload = 27,
    BeastMode = 28,
    Machina = 29,
    Years = 30,
    Frontlines = 31,
    SpacePirates = 32,
    Striker = 33,
    Embers = 34,
    Round1 = 35,
    MonsterDanceOff = 36,
    PressStart = 37,
    NockEm = 38,
    PowerTrip = 39
}
